### ISSUE TITLE
Improve Location Map Load Time

### ISSUE THREAD

**Issue by danieltsoukup** [CivicTechTO/tRacket-dashboard#35]
**Describe the bug**
Propose and implement a solution to improve the location map loading time - currently this is slow as we need to read for each location separately if it had sent data recently.

Options:
- implement a server side cache - we would have to fall back to a 24hr resolution but could allow to update this in the background automatically (currently active=sent data in the last hour)
- extend the API to allow pulling this information in a single query

[Update] API has been updated, see comments below. TODO:

1. add the new info in the data model https://github.com/CivicTechTO/tRacket-dashboard/blob/main/app/src/data_loading/models.py
2. extend the AppDataManager to make sure the latestTimestamp gets added and calculate the SENDING_DATA flag that was previously done by https://github.com/CivicTechTO/tRacket-dashboard/blob/main/app/src/data_loading/main.py
3. remove the calls to attach_all_location_stats() in the admin and locations page.

**Comment by mbechtel** [comment]
The backend already monitors all active sensors to notify sensor owners if they have not reported data in the last 30 minutes, 24 hours and 7 days.  The backend can be updated to leverage that process to efficiently include a "last_verified" timestamp in the location endpoint response, so additional API requests are not required to know if each location has been updated within the last hour.  I will follow-up here once that update has been made.  The last_verified property for each location will not represent the last time it was updated with a measurement, but a slightly less accurate (accurate within 1 hour) time of when the system last verified it had sent data.  While less accurate, it will be far more efficient to provide, keeping the locations endpoint as performant as possible while still providing the information we need.

**Comment by danieltsoukup** [comment]
That would be amazing, thanks, Mitch! I'm perfectly fine with that level of accuracy and we can communicate that on the dashboard.

**Comment by mbechtel** [comment]
Okay, the API has been updated.  The following new properties are returned for each location.

- **lastChecked** - The time the following properties were last checked for updates.  If no updates were available, the subsequent property values may not change, but lastChecked will always let you know when it measurements were last checked for updates.  This should generally be a time within the last 15 minutes, which is how often the summaries are updated.
- **latestTimestamp** - The time of the latest measurement as of the lastChecked time.  This is the timestamp that can be checked to see if the location has up to date data.  It is probably a good practice to verify that this time is from within the last hour to determine if the location has up to date data.
- **hourStart** - A timestamp representing the start of the latest hour of measurements collected.
- **hourStart** - A timestamp representing the end of the latest hour of measurements collected.
- **hourMin** - The minimum Min value measured between hourStart and hourEnd.
- **hourMax** - The maximum Max value measured between hourStart and hourEnd.
- **hourMean** - The average Mean value measured between hourStart and hourEnd.

Here is an example of the information now included in the response for each location.  The API Google Doc has also been updated, which will be moved to markdown in Github soon.
```
        {
            "id": 572227,
            "label": "Scott St. & Wellington St.",
            "latitude": 43.6481,
            "longitude": -79.376,
            "radius": 25,
            "active": true,
            "lastChecked": "2024-09-28T15:08:08-04:00",
            "latestTimestamp": "2024-07-06T14:03:00-04:00",
            "hourStart": "2024-07-06T13:03:00-04:00",
            "hourEnd": "2024-07-06T14:03:00-04:00",
            "hourMin": 2,
            "hourMax": 5,
            "hourMean": 2.555
        }
```

**Comment by danieltsoukup** [comment]
This is amazing, thanks @mbechtel  !!

On the dashboard side, this makes the changes much simpler:

1. add the new info in the data model https://github.com/CivicTechTO/tRacket-dashboard/blob/main/app/src/data_loading/models.py
2. extend the AppDataManager to make sure the `latestTimestamp` gets added and calculate the `SENDING_DATA` flag that was previously done by https://github.com/CivicTechTO/tRacket-dashboard/blob/main/app/src/data_loading/main.py
3. remove the calls to `attach_all_location_stats()` in the admin and locations page.

I think no downstream changes will be necessary and loading will be much faster 🤞

**Comment by danieltsoukup** [comment]
Done ✅
